name = "Cobblemon Refreshed Deluxe"
author = "ygoroffici"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7803179d8d6572848f0dd43802ee79a1dfdd7b50f0d68761210339b9cdd76117"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
datapack-folder = "./datapacks"
