name = "Cobblemon Refreshed Deluxe"
author = "ygoroffici"
version = "0.9.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d43a31ecc3d0fa4922d03a6ec610cd80af6334241556909a94c3daae8de3c07"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "./datapacks"
