name = "Cobblemon Refreshed Deluxe"
author = "ygoroffici"
version = "0.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2af37f26ad2558b0be99def673458801c776070caa6a225f6d9503a58f4fa170"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "./datapacks"
