name = "Cobblemon Refreshed Deluxe"
author = "ygoroffici"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a9b0814d66401ddee1dfaf9ad0926e17bfe67c6aedcc9eaf8142084f0493504"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"

[options]
datapack-folder = "./datapacks"
