name = "Cobblemon Refreshed Deluxe"
author = "ygoroffici"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad8eff39875c1c5073636e0b51d92ac5c432397840d760a93b1a66d0f3b5f35d"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
datapack-folder = "./datapacks"
